### PR TITLE
Introduce feature sendIntermediates (define, document, test)

### PR DESCRIPTION
**Pull request by jimklimov**
Follow-up to discussion at https://github.com/oetiker/znapzend/pull/455

CC @lotheac @oetiker

### CODE REVIEW

**Comment by lotheac** [comment]
On Fri, Nov 22 2019 08:28:06 +0000, Jim Klimov wrote:
> Follow-up to discussion at https://github.com/oetiker/znapzend/pull/455
> 
> CC @lotheac @oetiker
> You can view, comment on, or merge this pull request online at:

looks good to me, but not sure why you made it a PR to my fork, not
oetiker's :)

> 
>   https://github.com/lotheac/znapzend/pull/1
> 
> -- Commit Summary --
> 
>   * Introduce feature sendIntermediates (define, document, test)
> 
> -- File Changes --
> 
>     M bin/znapzend (26)
>     M doc/znapzend.pod (24)
>     M lib/ZnapZend.pm (3)
>     M lib/ZnapZend/ZFS.pm (4)
>     M man/znapzend.1 (23)
>     M t/znapzend.t (2)
> 
> -- Patch Links --
> 
> https://github.com/lotheac/znapzend/pull/1.patch
> https://github.com/lotheac/znapzend/pull/1.diff
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/lotheac/znapzend/pull/1

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Comment by jimklimov** [comment]
To inherit your commit, and eventually if you merge - the linked discussion at your original PR for the feature :)

**Comment by oetiker** [comment]
I like this, but the default should not change .. so maybe better have `skipIntermediates`. We use the -I feature to make sure that in case a send operation takes too long, we still get all the intermediate snapshots sent to the destionation ...

**Comment by jimklimov** [comment]
No problem with this on my side (even better so, per least-surprise principle). But Lauri may get upset :)

**Comment by jimklimov** [comment]
So updated the code and docs to revive the upstream's default. Also noted that for regular background `znapzend` services it may be beneficial to set this feature, at least in certain conditions (unsent snaps are not modus vivendi but a rare exception). Since this situation is not ubiquitous, not proposing changes into packaged pre-sets for the services :)

**Comment by jimklimov** [comment]
Hm... seems travis is not enabled in this fork :) I'll resubmit as PR to upstream...

**Comment by lotheac** [comment]
On Fri, Nov 22 2019 07:00:37 -0800, Jim Klimov wrote:
> No problem with this on my side (even better so, per least-surprise principle). But Lauri may get upset :)

nah, I can configure on my end ofc.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/lotheac/znapzend/pull/1#issuecomment-557564035

-- 
Lauri Tirkkonen | lotheac @ IRCnet

**Pull request closed without merging**
